---
title: ""
---

# MEINE ARBEIT

Ich begleite psychotherapeutisch körperlich schwerkranke Menschen, vor allem Krebspatientinnen und -patienten und ihre Zugehörigen. Dabei beschäftigen mich besonders existenzielle Themen: Hoffnung, Sinn, Leiden und Endlichkeit.

Daneben bin ich als Supervisor, Dozent und Autor tätig.

Praktische Erfahrungen habe ich in Göttingen und Hamburg in Psychotherapeutischen Hochschulambulanzen und auf Onkologischen, Pädiatrischen und Strahlentherapeutischen Akutstationen gesammelt.

Seit 2021 bin ich in privater Praxis, in der Ausbildung und Supervision von Psychotherapiekandidatinnen und -kandidaten (Institute IfP, DGVT, MOVA), in psychoonkologischen Seminaren sowie ehrenamtlich im Israelitischen Hospiz in Hamburg tätig.

Seit 2023 führe ich – organisiert durch die WPO – gemeinsam mit Dr. Katharina Scheffold Fortbildungen von „[CALM – Managing Cancer and Living Meaningfully](https://www.wpo-ev.de/portfolio/calm-psychoonkologische-kurzzeittherapie-bei-fortgeschrittener-tumorerkrankung)“, einer Kurzzeit-Psychotherapie für fortgeschritten erkrankte Krebspatienten und ihre Angehörigen durch.

Den Kern meiner psychotherapeutischen, wissenschaftlichen und lehrenden Tätigkeit bildet die Frage, wie wir Menschen, die massiven Belastungen durch die Behandlung und die schwere Erkrankung ausgesetzt sind, hilfreich und professionell begleiten können.
