---
title: ""
---

# IMPRESSUM

Dr. Frank Schulz-Kindermann, An der Alster 18, 20099 Hamburg; E-Mail: praxis-schulz-kindermann\@posteo.de

Kammermitglied bei der Psychotherapeutenkammer Hamburg; Eintrag im Arztregister Hamburg unter Nr. 71263

Kleinunternehmer im Sinne von §19 Abs. 1 Umsatzsteuergesetz (UStG) registriert beim Finanzamt Hamburg-Nord

### Informationen zu Haftung und Eigentumsrechten

#### Links zu externen Websites:

Die Inhalte externer Websites, auf die direkt oder indirekt verfwiesen wird, liegen außerhalb des Verantwortungsbereiches des Website-Inhabers. Der Website-Inhaber macht sich diese Inhalte nicht zu eigen und übernimmt keine Verantwortung für etwaige Inhalte oder Nachteile, die sich aus der Nutzung der auf den verlinkten Websites verfügbaren Informationen ergeben.

#### Copyrights und Markenrechte:

Alle auf dieser Website dargestellten Inhalte wie Texte, Fotos, Grafiken, Marken und Warenzeichen sind durch die entsprechenden Schutzrechte (Urheberrechte, Markenrechte) geschützt. Die Nutzung, Vervielfältigung usw. unterliegt unseren Rechten oder den Rechten der jeweiligen Autoren oder Rechteinhaber.
