---
title: ""
---

# VITA

Geboren 1958 in Kassel, seit 1991 in Hamburg, verheiratet, zwei erwachsene Kinder

#### **Akademische Laufbahn und Beruf**

-   Seit 2021: Tätigkeit in privater Praxis, An der Alster 18 in Hamburg

-   2006 - 2021: Leiter der Spezialambulanz für Psychoonkologie, Koordinator Klinische Versorgung, Institut für Medizinische Psychologie, UKE Hamburg

    -   DKG-Projekt: RCT CALM - Managing Cancer and Living Meaningfully

-   2001: Psychoonkologe (WPO); Supervisor (PTK)

-   1999: Approbation als Psychologischer Psychotherapeut, Fachkunde Verhaltenstherapie

-   1998: Promotion durch den Fachbereich Psychologie, Universität Hamburg; Thema der Dissertation: Krise und Trauma in der Strahlentherapie

-   1995 - 2006: Leiter Psychosozialer Dienst der Klinik für Stammzelltransplantation, UKE

    -   DFG-Projekt: Psychoonkologische Interventionen in der Stammzelltransplantation

-   seit 1992: Wissenschaftlicher Mitarbeiter Universitätsklinikum Hamburg-Eppendorf (UKE)

    -   DKG-Projekt: Psychosoziale Unterstützung in der Strahlentherapie

-   1987 - 1991: Wissenschaftliche Mitarbeiter, Institut für Klinische\
    Psychologie und Psychotherapie, Universität Göttingen

    -   Bundesmodell-Projekt: Beratungsmethoden bei HIV-Infektion und AIDS-Erkrankung

-   1987: Diplom in Psychologie, Universität Göttingen

#### **Psychotherapeutische Fort- und Weiterbildungen**

-   Verhaltenstherapie (DGVT)

-   Gesprächspsychotherapie (GwG)

-   Weiterbildung Psychosoziale Onkologie (WPO in der DKG)

-   Hypnotherapie (MEG)

-   Psychoimaginative Traumatherapie (PITT)

-   Managing Cancer & Living Meaningfully (CALM)

#### **Mitgliedschaften**

-   Psychotherapeutenkammer Hamburg

-   Deutsche Gesellschaft für Medizinische Psychologie (DGMP)

-   Hamburger Krebsgesellschaft (Mitglied des Vorstands)

-   Arbeitsgemeinschaft für Psychoonkologie in der DKG (PSO)

-   Weiterbildung Psychosoziale Onkologie e.V. (WPO)

-   Deutsche Gesellschaft für Palliativmedizin (DGP)

-   Deutsche Arbeitsgemeinschaft für Psychoonkologie - dapo
